version: "3.4"

services:
  nginx:
    container_name: nginx-${Node}
    image: nginx
    network_mode: host
    volumes:
      - "${Workdir}/nginx/html:/usr/share/nginx/html"
      - "${Workdir}/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "${Workdir}/nginx/conf.d/:/etc/nginx/conf.d/"
      - "${Workdir}/nginx/logs/:/var/log/nginx/"

  keepalived:
    container_name: keepalived-${Node}
    image: registry.cn-shenzhen.aliyuncs.com/zengql-release/keepalived:2.0.7
    network_mode: host
    restart: always
    privileged: true
    depends_on:
      - nginx
    volumes:
      - "${Workdir}/keepalived/:/usr/local/etc/keepalived/"

  consul:
    container_name: consul-${Node}
    command: agent -server -bind=${Host} -client=0.0.0.0 -retry-join=${ConsulJoinHost} -ui
    image: consul
    network_mode: host
    restart: always
    volumes:
      - "${Workdir}/consul/data:/consul/data"
      - "${Workdir}/consul/config:/consul/config"

  apollo-configservice:
    container_name: apollo-configservice-${Node}
    image: registry.cn-shenzhen.aliyuncs.com/zengql-release/apollo-configservice:1.0.0
    network_mode: host
    expose:
      - "8080"
    restart: always
    volumes:
      - "${Workdir}/apollo/configservice/logs:/opt/logs/100003171"
    environment:
      - spring_datasource_url=jdbc:mysql://${MysqlHost}/ApolloConfigDB?characterEncoding=utf8
      - spring_datasource_username=${MysqlUserName}
      - spring_datasource_password=${MysqlPassword}

  apollo-adminservice:
    container_name: apollo-adminservice-${Node}
    image: registry.cn-shenzhen.aliyuncs.com/zengql-release/apollo-adminservice:1.0.0
    network_mode: host
    expose:
      - "8090"
    restart: always
    depends_on:
      - apollo-configservice
    volumes:
      - "${Workdir}/apollo/adminservice/logs:/opt/logs/100003172"
    environment:
      - spring_datasource_url=jdbc:mysql://${MysqlHost}/ApolloConfigDB?characterEncoding=utf8
      - spring_datasource_username=${MysqlUserName}
      - spring_datasource_password=${MysqlPassword}

  apollo-portal:
    container_name: apollo-portal-${Node}
    image: registry.cn-shenzhen.aliyuncs.com/zengql-release/apollo-portal:1.0.0
    network_mode: host
    expose:
      - "8070"
    restart: always
    depends_on:
      - apollo-adminservice
    volumes:
      - "${Workdir}/apollo/portal/logs:/opt/logs/100003173"
    environment:
      - JAVA_OPTS=-Dpro_meta=http://pro.meta-server.zengql.local
      - spring_datasource_url=jdbc:mysql://${MysqlHost}/ApolloPortalDB?characterEncoding=utf8
      - spring_datasource_username=${MysqlUserName}
      - spring_datasource_password=${MysqlPassword}