version: "3.4"

services:
  consul:
    container_name: consul
    image: consul
    network_mode: host
    restart: always
    volumes:
      - ${Workdir}/consul/data:/data
    command: agent -bind=${Host} -client=0.0.0.0 -retry-join=${ConsulJoinHost}

  mysql:
    container_name: mysql
    image: mysql
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ${Workdir}/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MysqlPassword}

  mssql:
    container_name: mssql
    image: microsoft/mssql-server-linux
    ports:
      - 1433:1433
    restart: always
    volumes:
      - ${Workdir}/mssql/data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MssqlPassword}
